language: generic
os:
- linux
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda3-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: hzcOAqOT9NsV4uDWu38evUKlv+I8nm/X86p+wuuchcm0NU3ZV/SMaBc1O+nqHtQgzmiES9aLdGn1tz/2Z+yNPkGkAi0bpCmXhYloIYlD1BiZKJ5KJPFd0U3HgiDhlmjCJvD/SHu2nK/v4ewZRILJdV5rfBiS9vaVDyjrmcqGcPycAExgnyh5aSptIVmM7BEU4OnaTl8Oz8Zfe+GkVl5HDkNwEesCxQUfG9n4Ej3rrWvD0L1EHd6dr3QgUVQZHnWPIngtf/5CFNdQL4b2CupuA1eFROWf1iooDaGAIq1JWR8pluiLmyFFKknu2etiVn2E+Y044344baSvaZMgS+Ttgm6AKKuMnfzdajf17WZ37qypzEQ86Q+McqafXa9k1YIiAgqOb3RW9M8GPooeZpa0j4F/GuWv0Sc/Y8n9rLCgVaO94BpBZmqHu/74IthhlTi1fCtMDPdsfnq6UisxZZWJwGkumoCLoAq51kiapMzYprmN/k552nnmEGU4j8zu2FI3+Z7ysyLl/L0VFEtajZtEOSfahrC/0WB2PXnWniOV6bGImGr5328eRdVT2SQaR2rsR4DHiavC0D2Yx4qByUHbVOQu1s1tFJcFN2aW1Do+s7bRGLV/J5VajpASW95FO2sbTtumEJhuYUmoYVEOJUymocrPZZmAeaCi1YC5Ab/mQ/U=
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client coverage sphinx
script:
- conda build ./recipe -c csdms-stack -c conda-forge
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack
  --token=-
